debug: false
logging:
  level:
    root: info
  file:
    name: d:/Program Files/IdeaProjects/myspringboot.log

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.211.75.130/shixun202009?useSSL=false&userUnicode=\
      true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: edu
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

mall:
  config:
    name: 爱美商城
    description: 这是一家化妆品特卖网站
    hot-sales: 20
    show-advert: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



